export default {
    SET_URL_PARAMETER: 'SET_URL_PARAMETER',
    SET_UI_LANGUAGE: 'SET_UI_LANGUAGE',
    ADD_LOCATION: 'ADD_LOCATION',
    SET_MESSAGE: 'SET_MESSAGE',
    SET_BASIC_INFORMATION: 'SET_BASIC_INFORMATION',
    ADD_CALL: 'ADD_CALL',
    SET_LOGGED_IN: 'SET_LOGGED_IN',
    UPDATE_STATE: 'UPDATE_STATE'
};
